---
appname_marfile: tor-browser
appname_bundle_osx: TorBrowser
appname_bundle_linux: tor-browser
appname_bundle_win: torbrowser-install
releases_dir: ../../gitian
download:
    archive_url: https://archive.torproject.org/tor-package-archive/torbrowser
    gpg_keyring: ../../gitian/gpg/torbrowser.gpg
    bundles_url: https://dist.torproject.org/torbrowser
    mars_url: https://cdn.torproject.org/aus1/torbrowser
build_targets:
    linux32: Linux_x86-gcc3
    linux64: Linux_x86_64-gcc3
    win32:
        - WINNT_x86-gcc3
        - WINNT_x86-gcc3-x86
        - WINNT_x86-gcc3-x64
    osx32: Darwin_x86-gcc3
    osx64: Darwin_x86_64-gcc3
channels:
    alpha: 7.0a4
    release: 7.0.7
versions:
    7.0.7:
        platformVersion: 52.4.1
        detailsURL: https://blog.torproject.org/tor-browser-707-released
        incremental_from:
          - 7.0.6
        migrate_archs:
          osx32: osx64
        migrate_langs:
            pt-PT: pt-BR
        win32:
            minSupportedInstructionSet: SSE2
        osx32:
            minSupportedOSVersion: 13.0.0
        osx64:
            minSupportedOSVersion: 13.0.0
    7.0a4:
        platformVersion: 52.1.1
        detailsURL: https://blog.torproject.org/blog/tor-browser-70a4-released
        incremental_from:
          - 7.0a3
        migrate_archs:
          osx32: osx64
        migrate_langs:
            pt-PT: pt-BR
        win32:
            minSupportedInstructionSet: SSE2
        osx32:
            minSupportedOSVersion: 13.0.0
        osx64:
            minSupportedOSVersion: 13.0.0
